[package]
name = "ics-dm-iot-module-rs"
version = "0.1.2"
edition = "2018"
authors = ["Joerg Zeidler <joerg.zeidler@conplement.de>"]
repository = "git@github.com:ICS-DeviceManagement/ics-dm-iot-module-rs.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ics-dm-azure = { git = "ssh://git@github.com/ICS-DeviceManagement/ics-dm-azure-rs.git", branch = "main" }
serde_json = "1.0"
env_logger = "0.8"
log = "0.4"
