[package]
name = "ics-dm-iot-module-rs"
version = "0.1.0"
edition = "2018"
authors = ["Joerg Zeidler <joerg.zeidler@conplement.de>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ics-dm-azure-rs = { git = "ssh://git@github.com/ICS-DeviceManagement/ics-dm-azure-rs.git", branch = "setup" }
serde_json = "1.0"
